stages:
  - bump_version
  - release
  - release_notify

bump_version:
  stage: bump_version
  only:
    refs:
      - triggers
    variables:
      - $RELEASE

  image: buildpack-deps:disco-scm

  before_script:
    - git config user.email admin@getto.systems
    - git config user.name getto
    - curl https://raw.githubusercontent.com/getto-systems/git-post/master/scripts/setup.sh | bash -s -- ./vendor/getto-systems
    - export PATH=$PATH:./vendor/getto-systems/git-post/bin
  script:
    - cat ./dist/bump_version.sh | bash
    - cat ./dist/request.sh | bash -s -- ./.bump-message.sh

release:
  stage: release
  only:
    refs:
      - master@getto-systems-base/labo/ci/bump-version
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules

  script:
    - cat ./dist/push_tags.sh | bash
    - ./bin/deploy.sh

release_success:
  stage: release_notify
  only:
    refs:
      - master@getto-systems-base/labo/ci/bump-version
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_success

  image: buildpack-deps:disco-curl

  before_script:
    - export channel=$SLACK_CHANNEL
  script:
    - curl https://raw.githubusercontent.com/getto-systems/psycher-getto/master/bin/notify-release.sh | bash -s -- -l $GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true success

release_failure:
  stage: release_notify
  only:
    refs:
      - master@getto-systems-base/labo/ci/bump-version
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_failure

  image: buildpack-deps:disco-curl

  before_script:
    - export channel=$SLACK_CHANNEL
  script:
    - curl https://raw.githubusercontent.com/getto-systems/psycher-getto/master/bin/notify-release.sh | bash -s -- -l $GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true failure
