stages:
  - release
  - notify
  - push_tags

release:
  stage: release
  only:
    refs:
      - triggers
    variables:
      - $RELEASE

  image: buildpack-deps:disco-scm

  script:
    - ./bin/version_dump.sh
    - ./bin/version_dump_request_message.sh | ./bin/request.sh

release_success:
  stage: notify
  only:
    refs:
      - triggers
    variables:
      - $RELEASE
  when: on_success

  image: buildpack-deps:disco-curl

  script:
    - curl https://raw.githubusercontent.com/getto-systems/psycher-getto/master/bin/notify-deploy.sh | bash -s -- -l $GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true success

release_failure:
  stage: notify
  only:
    refs:
      - triggers
    variables:
      - $RELEASE
  when: on_failure

  image: buildpack-deps:disco-curl

  script:
    - curl https://raw.githubusercontent.com/getto-systems/psycher-getto/master/bin/notify-deploy.sh | bash -s -- -l $GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true failure

push_tags:
  stage: push_tags
  only:
    refs:
      - master@getto-systems-base/projects/version-dump
    changes:
      - .release-version
  except:
    refs:
      - schedules
      - triggers

  image: buildpack-deps:disco-scm

  script:
    - ./bin/push_tags.sh
