stages:
  - bump_version
  - release
  - release_notify

variables:
  TRELLIS_HANGAR: https://trellis.getto.systems/hangar/3.5.0
  TRELLIS_GIT_POST: https://trellis.getto.systems/git/post/1.0.0
  TRELLIS_PSYCHER_GETTO: https://trellis.getto.systems/psycher/getto/2.6.0

bump_version:
  stage: bump_version
  only:
    refs:
      - triggers
    variables:
      - $RELEASE

  image: buildpack-deps:buster-scm

  before_script:
    - git config user.email admin@getto.systems
    - git config user.name getto
    - curl $TRELLIS_GIT_POST/setup.sh | sh -s -- ./vendor/getto-systems
    - export PATH=$PATH:./vendor/getto-systems/git-post/bin
  script:
    - cat ./dist/bump_version.sh | bash
    - cat ./dist/request.sh | bash -s -- ./.message/bump.sh

release:
  stage: release
  only:
    refs:
      - release@getto-systems-base/labo/ci/bump-version
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules

  script:
    - cat ./dist/push_tags.sh | sh
    - ./scripts/deploy.sh

release_success:
  stage: release_notify
  only:
    refs:
      - release@getto-systems-base/labo/ci/bump-version
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_success

  image: buildpack-deps:buster-curl

  before_script:
    - export url=$GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true
    - export channel=$SLACK_CHANNEL
    - export version=bump-version:$(cat .release-version)
  script:
    - curl $TRELLIS_PSYCHER_GETTO/notify-release-success.sh | sh -s -- $url $channel $version

release_failure:
  stage: release_notify
  only:
    refs:
      - release@getto-systems-base/labo/ci/bump-version
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_failure

  image: buildpack-deps:buster-curl

  before_script:
    - export url=$GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true
    - export channel=$SLACK_CHANNEL
    - export version=bump-version:$(cat .release-version)
  script:
    - curl $TRELLIS_PSYCHER_GETTO/notify-release-failure.sh | sh -s -- $url $channel $version
